theme: theme/compass

deploy:
  type: git
  token: "${GIT_TOKEN}"
  remote: https://github.com/zbysir/zbysir.github.io
  branch: docs

source:
  type: git
  token: "${GIT_TOKEN}"
  remote: https://github.com/zbysir/zbysir.github.io
  branch: master

file:
  img_compression:
    scope: "only_blog" # all：全部静态资源中的图片，only_blog：出现在文章引用中
    width:
    height:
    q:

oss:
  type: qiniu
  access_key: "${QINIU_AK}"
  secret_key: "${QINIU_SK}"
  bucket: bysirblogout
  prefix: blog
  domain: http://blog-static.bysir.top

# 将会 copy 到根目录
assets:
  - statics

# theme_config 字段的值可以在 js 中使用 bblog.getConfig() 获取
theme_config:
  base: ''
  title: Hollow
  logo: "Hollow"
  stack: Tailwindcss + <a href="https://github.com/zbysir/hollow">Hollow</a>
  footer_links:
    - link: https://github.com/zbysir
      name: GitHub
      icon: GitHub
  home_page: 'pages/home.html'
